### ISSUE TITLE
Disconnected SQL generation does not work

### ISSUE THREAD

**Issue by ap** [alranel/DBIx-Lite#11]
`$resultset->select_sql` calls `$resultset->_table_alias` which calls `$dbix_lite->driver_name` which calls `$dbix_lite->dbh` without arguments which croaks if the DBIx::Lite does not have a database connection.

Thus, no database handle or connection, no SQL.

There ought to be tests that make sure disconnected SQL generation works.

**Comment by alexrj** [comment]
Good point.

**Comment by alranel** [comment]
Disconnected mode is now fixed. Better late than never, right? 😅

**Comment by ap** [comment]
Absolutely!

**Comment by ap** [comment]
But why is it not indexed on CPAN any more?
