### ISSUE TITLE
unable to use select_sql without a database handle

### ISSUE THREAD

**Issue by djerius** [alranel/DBIx-Lite#14]
DBIx::Lite::VERSION = 0.31

I'm trying to generate some SQL without connecting to a database, and I believe something like the following should work:

    DBIx::Lite->new->table('foo')->select_sql

However, I'm getting the following error message:

    No database handle or DBIx::Connector object provided

Thanks,
Diab

**Comment by alranel** [comment]
Thank you for the report. This is related to #11

**Comment by alranel** [comment]
This is now fixed. Use this:

```
DBIx::Lite->new(driver_name => 'Pg')->table('foo')->select_sql
```
