### ISSUE TITLE
SELECT DISTINCT available only via hack

### ISSUE THREAD

**Issue by djerius** [alranel/DBIx-Lite#15]
$DBIx::Lite::VERSION = 0.31

I'm trying to generate a `SELECT DISTINCT` statement.  The underlying [SQL::Abstract::More](https://metacpan.org/pod/SQL::Abstract::More) module uses the following syntax:

    -columns  => [-distinct => qw/col1 col2/],

But that doesn't work with `DBIx::Lite`:

    $pg->table( 'arc4gl_keywd' )->select( -distinct => '*' )->select_sql

returns

    'SELECT me.-distinct, me.* FROM arc4gl_keywd AS me'

Instead I have to do this:

    $pg->table( 'arc4gl_keywd' )->from('arc4gl_keywd')->select( -distinct => '*' )->select_sql;

to get

    'SELECT distinct * FROM arc4gl_keywd'

Thanks,
Diab

**Comment by djerius** [comment]
escaping the `-distinct` by passing it as a scalar ref suffices, e.g.
```
$pg->table( 'arc4gl_keywd' )->select( \'-distinct' => '*' )->select_sql
```

**Comment by alranel** [comment]
FYI, a new `->distinct` method is now available, supporting also the `DISTINCT ON ()` syntax.

**Comment by djerius** [comment]
Thanks!
