### ISSUE TITLE
pk() method implementation inconsistent with documentation

### ISSUE THREAD

**Issue by mreitinger** [alranel/DBIx-Lite#17]
The pk() method accepts, according to the documentation, multiple primary keys in following format:

```->pk('key1', 'key2');```

This will result in a rather hard to debug issue since the check against ARRAY in pk() will fail and only the first key will be used. Only by passing a array ref the check will succeed and actually use all of the keys:

```->pk(['key1', 'key2']```

The following code illustrates this issue:

```
use DBIx::Lite;
use Data::Dumper;

my $dbix = DBIx::Lite->new;

my $table1 = $dbix->schema->table('dummy1');
$table1->pk('key1', 'key2');
my @keys1 = $table1->pk;
print "pk called with two values: " . Dumper(\@keys1) . "\n";;

my $table2 = $dbix->schema->table('dummy2');
$table2->pk(['key1', 'key2']);
my @keys2 = $table2->pk;
print "pk called with hashref: " . Dumper(\@keys2) . "\n";
```

**Comment by alranel** [comment]
Thank you for reporting this, and sorry for the delay. I fixed it.
